/*
  Constants.js
  공통 파일 - 임의 수정 금지
  역할: 게임 단계, 이벤트명, 기본 설정값 관리
*/

export const GAME_PHASE = {
  READY: "READY",
  DAY_START: "DAY_START",
  ORDER: "ORDER",
  STORE_OPEN: "STORE_OPEN",
  STORE_RUNNING: "STORE_RUNNING",
  DAY_END: "DAY_END",
  RESULT: "RESULT",
  UPGRADE: "UPGRADE",
  NEXT_DAY: "NEXT_DAY",
  ENDLESS: "ENDLESS"
};

export const EVENTS = {
  GAME_INIT: "GAME_INIT",

  DAY_START_REQUESTED: "DAY_START_REQUESTED",
  DAY_STARTED: "DAY_STARTED",

  ORDER_PHASE_STARTED: "ORDER_PHASE_STARTED",
  ORDER_MODAL_OPENED: "ORDER_MODAL_OPENED",
  ORDER_BUTTON_CLICKED: "ORDER_BUTTON_CLICKED",
  ORDER_REQUESTED: "ORDER_REQUESTED",
  ORDER_CONFIRMED: "ORDER_CONFIRMED",
  ORDER_DELIVERED: "ORDER_DELIVERED",
  STOCK_ORGANIZED: "STOCK_ORGANIZED",

  STORE_OPEN_REQUESTED: "STORE_OPEN_REQUESTED",
  STORE_OPENED: "STORE_OPENED",

  STORE_CLOSE_REQUESTED: "STORE_CLOSE_REQUESTED",
  STORE_CLOSED: "STORE_CLOSED",

  DAY_ENDED: "DAY_ENDED",
  RESULT_CALCULATED: "RESULT_CALCULATED",

  UPGRADE_PHASE_STARTED: "UPGRADE_PHASE_STARTED",
  UPGRADE_SELECTED: "UPGRADE_SELECTED",

  NEXT_DAY_READY: "NEXT_DAY_READY",
  GAME_STATE_CHANGED: "GAME_STATE_CHANGED",

  EXPANSION_REQUESTED: "EXPANSION_REQUESTED",
  EXPANSION_COMPLETED: "EXPANSION_COMPLETED",
  EXPANSION_FAILED: "EXPANSION_FAILED",

  ENDING_ACHIEVED: "ENDING_ACHIEVED",
  ENDING_MODAL_CLOSED: "ENDING_MODAL_CLOSED",

  PLAYER_ACTION_RECORDED: "PLAYER_ACTION_RECORDED",
  CHECKOUT_COMPLETED: "CHECKOUT_COMPLETED",
  RESTOCK_COMPLETED: "RESTOCK_COMPLETED",
  CLEANING_COMPLETED: "CLEANING_COMPLETED",

  CUSTOMER_ENTERED: "CUSTOMER_ENTERED",
  CUSTOMER_SATISFIED: "CUSTOMER_SATISFIED",
  CUSTOMER_ANGRY: "CUSTOMER_ANGRY",
  CUSTOMER_LEFT: "CUSTOMER_LEFT",

  REVENUE_CHANGED: "REVENUE_CHANGED",
  COST_CHANGED: "COST_CHANGED",
  INVENTORY_CHANGED: "INVENTORY_CHANGED",
  EXPIRED_LOSS_RECORDED: "EXPIRED_LOSS_RECORDED",
  EVENT_PENALTY_RECORDED: "EVENT_PENALTY_RECORDED",
  BM_BONUS_APPLIED: "BM_BONUS_APPLIED"
};

export const GAME_CONFIG = {
  MAX_STORY_DAY: 5,
  DEFAULT_DAY_TIME_SECONDS: 180,
  START_MONEY: 10000,
  START_MENTAL: 100,
  START_SATISFACTION: 100
};
